package main

import (
	"context"
	"errors"
	"log/slog"
	"net/http"
	"os"
	"os/signal"
	"strings"
	"syscall"
	"time"

	"github.com/mohitbadwal/team-relay/internal/auth"
	"github.com/mohitbadwal/team-relay/internal/collaboration"
	"github.com/mohitbadwal/team-relay/internal/server"
	"github.com/mohitbadwal/team-relay/internal/store"
	"github.com/redis/go-redis/v9"
)

func main() {
	logger := slog.New(slog.NewJSONHandler(os.Stdout, &slog.HandlerOptions{Level: slog.LevelInfo}))
	if len(os.Args) == 2 && os.Args[1] == "healthcheck" {
		if err := healthcheck(); err != nil {
			logger.Error("healthcheck failed", "err", err)
			os.Exit(1)
		}
		return
	}
	if err := run(logger); err != nil {
		logger.Error("team relay server stopped", "err", err)
		os.Exit(1)
	}
}

func healthcheck() error {
	endpoint := envOrDefault("TEAM_RELAY_HEALTH_URL", "http://127.0.0.1:8080/health/ready")
	client := &http.Client{Timeout: 2 * time.Second}
	response, err := client.Get(endpoint)
	if err != nil {
		return err
	}
	defer response.Body.Close()
	if response.StatusCode != http.StatusOK {
		return errors.New("relay is not ready")
	}
	return nil
}

func run(logger *slog.Logger) error {
	redisURL := envOrDefault("REDIS_URL", "redis://127.0.0.1:6379/0")
	options, err := redis.ParseURL(redisURL)
	if err != nil {
		return errors.New("REDIS_URL is invalid")
	}
	rdb := redis.NewClient(options)
	defer rdb.Close()

	startupContext, cancelStartup := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancelStartup()
	if err := rdb.Ping(startupContext).Err(); err != nil {
		return errors.New("Redis or Valkey is unavailable")
	}

	repository := store.NewRedis(rdb)
	bootstrapToken, err := readBootstrapToken()
	if err != nil {
		return err
	}
	initialized, err := repository.IsBootstrapped(startupContext)
	if err != nil {
		return errors.New("could not read bootstrap state")
	}
	if !initialized && bootstrapToken == "" {
		return errors.New("set TEAM_RELAY_BOOTSTRAP_TOKEN_FILE before the first start")
	}
	if bootstrapToken != "" {
		kind, tokenErr := auth.Kind(bootstrapToken)
		if tokenErr != nil || kind != auth.TokenBootstrap {
			return errors.New("bootstrap token must be generated by team-relay-admin generate-bootstrap-token")
		}
	}

	collaborationStore := collaboration.NewRedisStore(rdb)
	hub := collaboration.NewHub()
	adminHandler := server.NewHandler(repository, server.Config{
		BootstrapToken:    bootstrapToken,
		RevocationEvicter: collaboration.NewRevocationEvicter(collaborationStore, hub),
	}, logger)
	mux := http.NewServeMux()
	adminHandler.RegisterRoutes(mux)
	collaboration.NewHandler(collaborationStore, adminHandler.AuthenticateRequest, hub, logger).RegisterRoutes(mux)
	handler := server.WithSecurityHeaders(mux)
	address := envOrDefault("TEAM_RELAY_ADDR", "127.0.0.1:8080")
	httpServer := &http.Server{
		Addr:              address,
		Handler:           handler,
		ReadTimeout:       15 * time.Second,
		ReadHeaderTimeout: 5 * time.Second,
		WriteTimeout:      0, // collaboration SSE connections are long lived
		IdleTimeout:       120 * time.Second,
	}

	serverErrors := make(chan error, 1)
	go func() {
		logger.Info("team relay server listening", "address", address, "initialized", initialized)
		serverErrors <- httpServer.ListenAndServe()
	}()

	signals := make(chan os.Signal, 1)
	signal.Notify(signals, syscall.SIGINT, syscall.SIGTERM)
	defer signal.Stop(signals)
	select {
	case signal := <-signals:
		logger.Info("shutting down", "signal", signal.String())
		shutdownContext, cancelShutdown := context.WithTimeout(context.Background(), 10*time.Second)
		defer cancelShutdown()
		return httpServer.Shutdown(shutdownContext)
	case err := <-serverErrors:
		if errors.Is(err, http.ErrServerClosed) {
			return nil
		}
		return err
	}
}

func readBootstrapToken() (string, error) {
	filePath := strings.TrimSpace(os.Getenv("TEAM_RELAY_BOOTSTRAP_TOKEN_FILE"))
	direct := strings.TrimSpace(os.Getenv("TEAM_RELAY_BOOTSTRAP_TOKEN"))
	if filePath != "" && direct != "" {
		return "", errors.New("set only one of TEAM_RELAY_BOOTSTRAP_TOKEN_FILE and TEAM_RELAY_BOOTSTRAP_TOKEN")
	}
	if filePath == "" {
		return direct, nil
	}
	value, err := os.ReadFile(filePath)
	if err != nil {
		return "", errors.New("could not read TEAM_RELAY_BOOTSTRAP_TOKEN_FILE")
	}
	return strings.TrimSpace(string(value)), nil
}

func envOrDefault(name, fallback string) string {
	if value := strings.TrimSpace(os.Getenv(name)); value != "" {
		return value
	}
	return fallback
}
